In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from simulator import LossSimulation

In [28]:
unit_sales_per_day = 10
units_per_case = 4
codelife = 5
lead_time = 3
total_days = 1000
max_stockout_probability = 0.7

sim = LossSimulation(codelife, unit_sales_per_day, units_per_case, lead_time)

min_loss, min_threshold, losses = sim.calculate_min_loss(total_days = total_days, rotation = True, granularitys=(10, 6), multipliers=(1,2))
threshold, total_loss, availability_loss, waste_loss = losses

min_loss_mean, min_loss_std = sim.calculate_min_loss_variance(total_days = total_days, stockout_threshold=min_threshold)

min_loss_mean, min_loss_std

Before the multiplier, each simulation will run for 45 days
INITIAL SEARCH COMPLETE
Stockout Thresholds: [1.00000000e-04 1.11088889e-01 2.22077778e-01 3.33066667e-01
 4.44055556e-01 5.55044444e-01 6.66033333e-01 7.77022222e-01
 8.88011111e-01 9.99000000e-01]
Min Loss: [0.         0.11111111 0.24444444 0.15555556 0.33333333 0.53333333
 0.57777778 0.73333333 0.62222222 0.95555556]
NARROWED SEARCH WINDOW
Stockout Thresholds: [0.         0.03331667 0.06663333 0.09995    0.13326667 0.16658333]
Min Loss: [0.15874704 0.08888889 0.14444444 0.07777778 0.1        0.07777778]
[0.1  0.13 0.1  0.12 0.09 0.14 0.14 0.17 0.2  0.14]


(0.133, 0.03195309061734092)

In [24]:
min_loss_mean, min_loss_std = sim.calculate_min_loss_variance(total_days = 10000, stockout_threshold=1e-3)

[0.02       0.01401626 0.012      0.025      0.01261224 0.01729727
 0.0145071  0.01230108 0.011      0.01210012]


In [25]:
min_loss_mean

0.01508340736587851

In [26]:
days_restock, a_loss, w_loss = sim.naive_get_min_availability_waste()
a_loss + w_loss, a_loss, w_loss

(0.0034125613871467788, 0.0, 0.0034125613871467788)

In [22]:
sim.simulate(total_days = 100, stockout_threshold=0.5, rotation = True, verbose = 2)


Day 0 [0] [5] 1.0
Day 0 Active Groups: [0]
Day 0 ordered more stock
Day 0 [0 4] [5 8] 0.01898814701917584
Sales today: nothing to sell
Day 0 Wasted Units: 0
Day 0 Stockout: True

Day 1 [4] [7] 0.14287653909006082
Day 1 Active Groups: []
Sales today: nothing to sell
Day 1 Wasted Units: 0
Day 1 Stockout: True

Day 2 [4] [6] 0.35276811116395534
Day 2 Active Groups: []
Sales today: nothing to sell
Day 2 Wasted Units: 0
Day 2 Stockout: True

Day 3 [4] [5] 0.566529879629009
Day 3 Active Groups: [0]
Day 3 ordered more stock
Day 3 [4 4] [5 8] 0.004342128843854948
Sales today: 1
Day 3 Wasted Units: 0
Day 3 Stockout: False

Day 4 [3 4] [4 7] 0.049937636154231975
Day 4 Active Groups: [0]
Sales today: 1
Day 4 Wasted Units: 0
Day 4 Stockout: False

Day 5 [2 4] [3 6] 0.1952536067198296
Day 5 Active Groups: [0]
Sales today: 0
Day 5 Wasted Units: 0
Day 5 Stockout: False

Day 6 [2 4] [2 5] 0.2563850604035691
Day 6 Active Groups: [0 1]
Sales today: 0
Day 6 Wasted Units: 0
Day 6 Stockout: False

Day 7 [

(array([0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0]),
 array([ True,  True,  True, False, False, False, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False,  True,  True, False, False, False,
        False, False, False, Fal